source 'http://rubygems.org'

gem 'rails', '3.0.7'
gem 'mysql2', '~> 0.2.7'
gem 'SystemTimer'
gem 'ruby-audioinfo'
gem 'oa-core'
gem 'oa-oauth'
gem 'yajl-ruby'
gem 'jrails'
gem 'haml'
gem 'paperclip', '~> 2.3'
gem 'css3buttons'
gem "bcrypt-ruby", :require => "bcrypt"
gem 'meta_search'
gem 'meta_where'